/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.naufaltrix.joindb;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author latitude
 */
public class tabeldata extends javax.swing.JFrame {
    Statement st;
    ResultSet rs;
    koneksi koneksi;
    /**
     * Creates new form tabeldata
     */
    public tabeldata() {
        koneksi = new koneksi();
        initComponents();
    }
    private void semuadata() {
            Object header[]={"Nim","Nama","Tgl Lahir","Jurusan", "Alamat","Fakultas"};
            DefaultTableModel data = new DefaultTableModel(null, header);
            tabel1.setModel(data);

            String sql = "SELECT A.nim, A.nama, A.tanggal_lahir, A.jurusan, A.alamat ,B.fak_nama FROM (mahasiswa AS A)\n" +
                            "INNER JOIN fakultas AS B ON (A.fak_id = B.fak_id)";
            try {
               st = koneksi.con.createStatement();
               rs = st.executeQuery(sql);
               while(rs.next()){
                   String kolom1 = rs.getString(1);
                   String kolom2 = rs.getString(2);
                   String kolom3 = rs.getString(3);
                   String kolom4 = rs.getString(4);
                   String kolom5 = rs.getString(5);
                   String kolom6 = rs.getString(6);

                   String kolom[] = {kolom1, kolom2, kolom3, kolom4, kolom5, kolom6};
                   data.addRow(kolom);
                   }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null,"error :"+e.getMessage());
            }
    }
    private void semuadata2() {
            Object header[]={"Id Fakultas", "Nama Fakultas"};
            DefaultTableModel data = new DefaultTableModel(null, header);
            tabel2.setModel(data);

            String sql = "SELECT * FROM fakultas";
            try {
               st = koneksi.con.createStatement();
               rs = st.executeQuery(sql);
               while(rs.next()){
                   String kolom1 = rs.getString(1);
                   String kolom2 = rs.getString(2);
                   

                   String kolom[] = {kolom1, kolom2};
                   data.addRow(kolom);
                   }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null,"error :"+e.getMessage());
            }
    }
    private void semuadata3() {
            Object header[]={"Id Pelajaran", "Mata Pelajaran"};
            DefaultTableModel data = new DefaultTableModel(null, header);
            tabel3.setModel(data);

            String sql = "SELECT * FROM pelajaran";
            try {
               st = koneksi.con.createStatement();
               rs = st.executeQuery(sql);
               while(rs.next()){
                   String kolom1 = rs.getString(1);
                   String kolom2 = rs.getString(2);
                   

                   String kolom[] = {kolom1, kolom2};
                   data.addRow(kolom);
                   }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null,"error :"+e.getMessage());
            }
    }
    private void semuadata4() {
            Object header[]={"Nip Dosen", "Nama", "Status", "Fakultas", "Pelajaran"};
            DefaultTableModel data = new DefaultTableModel(null, header);
            tabel4.setModel(data);

            String sql = "SELECT A.dosen_nip, A.dosen_nama, A.dosen_status, B.fak_nama, C.pel_nama FROM (dosen AS A)\n" +
                         "INNER JOIN fakultas AS B ON (A.fak_id = B.fak_id)\n" +
                         "INNER JOIN pelajaran AS C ON (A.pel_id = C.pel_id) WHERE A.dosen_status = 1";
            try {
               st = koneksi.con.createStatement();
               rs = st.executeQuery(sql);
               while(rs.next()){
                   String kolom1 = rs.getString(1);
                   String kolom2 = rs.getString(2);
                   String kolom3 = rs.getString(3);
                   String kolom4 = rs.getString(4);
                   String kolom5 = rs.getString(5);
                   

                   String kolom[] = {kolom1, kolom2, kolom3, kolom4, kolom5};
                   data.addRow(kolom);
                   }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null,"error :"+e.getMessage());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Tampil Semua Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel1);

        jTabbedPane1.addTab("Biodata", jScrollPane1);

        tabel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabel2);

        jTabbedPane1.addTab("Fakultas", jScrollPane2);

        tabel3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabel3);

        jTabbedPane1.addTab("Pelajaran", jScrollPane3);

        tabel4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabel4);

        jTabbedPane1.addTab("Dosen", jScrollPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        semuadata();
        semuadata2();
        semuadata3();
        semuadata4();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabeldata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabeldata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabeldata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabeldata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabeldata().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabel1;
    private javax.swing.JTable tabel2;
    private javax.swing.JTable tabel3;
    private javax.swing.JTable tabel4;
    // End of variables declaration//GEN-END:variables
}
